export const chessPiecesBlack = [
    {
        name : "leftRook",
        row : 0,
        col : 0,
        piece : "♜",
        selected : false,
    },
    {
        name : "leftKnight",
        row : 0,
        col : 1,
        piece : "♞",
        selected : false,
    },
    {
        name : "leftBishop",
        row : 0,
        col : 2,
        piece : "♝",
        selected : false,
    },
    {
        name : "queen",
        row : 0,
        col : 3,
        piece : "♛",
        selected : false,
    },
    {
        name : "king",
        row : 0,
        col : 4,
        piece : "♚",
        selected : false,
    },
    {
        name : "rightBishop",
        row : 0,
        col : 5,
        piece : "♝",
        selected : false,
    },
    {
        name : "rightKnight",
        row : 0,
        col : 6,
        piece : "♞",
        selected : false,
    },
    {
        name : "rightRook",
        row : 0,
        col : 7,
        piece : "♜",
        selected : false,
    },
    {
        name : "pawn1",
        row : 1,
        col : 0,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn2",
        row : 1,
        col : 1,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn3",
        row : 1,
        col : 2,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn4",
        row : 1,
        col : 3,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn5",
        row : 1,
        col : 4,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn6",
        row : 1,
        col : 5,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn7",
        row : 1,
        col : 6,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn8",
        row : 1,
        col : 7,
        piece : "♟",
        selected : false,
    },
]

export const chessPiecesWhite = [
    {
        name : "leftRook",
        row : 7,
        col : 0,
        piece : "♜",
        selected : false,
    },
    {
        name : "leftKnight",
        row : 7,
        col : 1,
        piece : "♞",
        selected : false,
    },
    {
        name : "leftBishop",
        row : 7,
        col : 2,
        piece : "♝",
        selected : false,
    },
    {
        name : "queen",
        row : 7,
        col : 3,
        piece : "♛",
        selected : false,
    },
    {
        name : "king",
        row : 7,
        col : 4,
        piece : "♚",
        selected : false,
    },
    {
        name : "rightBishop",
        row : 7,
        col : 5,
        piece : "♝",
        selected : false,
    },
    {
        name : "rightKnight",
        row : 7,
        col : 6,
        piece : "♞",
        selected : false,
    },
    {
        name : "rightRook",
        row : 7,
        col : 7,
        piece : "♜",
        selected : false,
    },
    {
        name : "pawn1",
        row : 6,
        col : 0,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn2",
        row : 6,
        col : 1,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn3",
        row : 6,
        col : 2,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn4",
        row : 6,
        col : 3,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn5",
        row : 6,
        col : 4,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn6",
        row : 6,
        col : 5,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn7",
        row : 6,
        col : 6,
        piece : "♟",
        selected : false,
    },
    {
        name : "pawn8",
        row : 6,
        col : 7,
        piece : "♟",
        selected : false,
    },
]